// Generated by CoffeeScript 1.3.3
(function() {
  var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  window.curr_letter = '';

  window.last_city = '';

  window.used_cities = [];

  window.error = '';

  window.handleInputKeyup = function(evt) {
    if (evt.keyCode === 13) {
      return handleSubmit();
    }
  };

  window.handleSubmit = function() {
    var cityname, isValid;
    cityname = $.trim($('input[name=city_name]').val());
    isValid = isValidCity(cityname);
    updateDisplay(isValid);
    return handleComputerTurn();
  };

  window.isValidCity = function(input_city) {
    var city, city_list_starting_with, country_id, first_letter, list_city, tuple, _i, _len;
    first_letter = input_city[0].toUpperCase();
    city = first_letter + input_city.substr(1);
    if (!cities.hasOwnProperty(first_letter)) {
      window.error = "The first letter of your city is not in the English alphabet.";
      return false;
    }
    if (__indexOf.call(used_cities, city) >= 0) {
      window.error = "You've used that city already!";
      return false;
    }
    city_list_starting_with = cities[first_letter];
    for (_i = 0, _len = city_list_starting_with.length; _i < _len; _i++) {
      tuple = city_list_starting_with[_i];
      list_city = tuple[0];
      country_id = tuple[1];
      if (city === list_city) {
        $('.status').text("You got it!  " + list_city + " is in " + countries[country_id]);
        window.last_city = list_city;
        used_cities.push(list_city);
        $('input[name=city_name]').val('');
        return true;
      }
    }
    window.error = input_city + " is NOT a valid city.";
    return false;
  };

  window.updateDisplay = function(cityIsValid) {
    if (!cityIsValid) {
      handleErrors();
    }
    $('.streak').text(used_cities);
    return $('.count').text(used_cities.length);
  };

  window.handleComputerTurn = function(valid) {
    if (valid) {
      return setTimeout(computerTurn, 1000);
    }
  };

  window.computerTurn = function() {
    return $('.status').text("Computer's turn...");
  };

  window.handleErrors = function() {
    return $('.status').text(window.error);
  };

  window.runTestCases = function() {
    testIsValid('Stanford');
    testIsInvalid('Pirateville');
    testIsValid('dubai');
    return testIsValid('Belem');
  };

  window.testIsValid = function(cityname) {
    var $result, passed;
    passed = isValidCity(cityname);
    $result = $('<div />').text("Testing that " + cityname + " is valid ... " + resultText(passed));
    $result.css('color', resultColor(passed));
    return $('.testresults').append($result);
  };

  window.testIsInvalid = function(cityname) {
    var $result, passed;
    passed = !isValidCity(cityname);
    $result = $('<div />').text("Testing that " + cityname + " is not valid ... " + resultText(passed));
    $result.css('color', resultColor(passed));
    return $('.testresults').append($result);
  };

  window.resultText = function(passed) {
    if (passed) {
      return 'Passed';
    } else {
      return 'Failed';
    }
  };

  window.resultColor = function(passed) {
    if (passed) {
      return 'green';
    } else {
      return 'red';
    }
  };

}).call(this);
